Another Insurance Company (C#. NET)/AnotherInsuranceCompany/Controllers/QuoteController.cs
using AnotherInsuranceCompany.Models;
using System;
using System.Web.Mvc;

namespace AnotherInsuranceCompany.Controllers
{
    public class QuoteController : Controller
    
    {
        // GET: Quote
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Apply(string firstName, string lastName, string emailAddress,
                             DateTime dateOfBirth, int carYear, string carMake, string carModel,
                             string dui, int tickets, string coverage, string total)
        {
            if (string.IsNullOrEmpty(firstName) || string.IsNullOrEmpty(lastName) || string.IsNullOrEmpty(emailAddress) ||
                string.IsNullOrEmpty(dateOfBirth.ToString()) || string.IsNullOrEmpty(carYear.ToString()) || string.IsNullOrEmpty(carMake) ||
                string.IsNullOrEmpty(carModel) || string.IsNullOrEmpty(dui) || string.IsNullOrEmpty(tickets.ToString()) || string.IsNullOrEmpty(coverage))
            {
                return View("~/Views/Shared/Error.cshtml");
            }
            else
            {
                using (AnotherInsuranceEntities db = new AnotherInsuranceEntities())
                {
                    var user = new Applicant();
                    user.FirstName = firstName;
                    user.LastName = lastName;
                    user.EmailAddress = emailAddress;
                    user.DateOfBirth = dateOfBirth;
                    user.CarYear = carYear;
                    user.CarMake = carMake;
                    user.CarModel = carModel;
                    user.DUI = dui;
                    user.SpeedingTickets = tickets;
                    user.CoverageType = coverage;
                    user.Total = quoteTotal(dateOfBirth,
                                       carYear,
                                       carMake,
                                       carModel,
                                       dui,
                                       tickets,
                                       coverage);

                    db.Applicants.Add(user);
                    db.SaveChanges();

                    ViewData["user.Total"] = user.Total;
                    return View("Index");
                }
            }
        }


        public int quoteTotal(DateTime dateOfBirth, int carYear, string carMake, string carModel,
                                  string dui, int tickets, string coverage)
        {
            using (AnotherInsuranceEntities data = new AnotherInsuranceEntities())
            {
                int totalQuote = 50;

                // Quote based on Age
                totalQuote = (DateTime.Now.Year - (Convert.ToDateTime(dateOfBirth)).Year < 18) ? totalQuote + 100 : totalQuote;
                totalQuote = (DateTime.Now.Year - (Convert.ToDateTime(dateOfBirth)).Year <= 25) ? totalQuote + 50 : totalQuote;
                totalQuote = (DateTime.Now.Year - (Convert.ToDateTime(dateOfBirth)).Year > 25) ? totalQuote + 25 : totalQuote;
                
                // Quote based on Car
                totalQuote = (Convert.ToInt32(carYear) < 2000) ? totalQuote + 25 : totalQuote;
                totalQuote = (Convert.ToInt32(carYear) > 2015) ? totalQuote + 25 : totalQuote;
                totalQuote = (carMake.ToLower() == "porsche") ? totalQuote + 25 : totalQuote;
                totalQuote = (carModel.ToLower() == "911 carrera") ? totalQuote + 25 : totalQuote;

                // Tickets and DUI's
                totalQuote = totalQuote + (Convert.ToInt32(tickets) * 10);
                totalQuote = (dui.ToLower() == "yes") ? (totalQuote + (totalQuote / 4)) : totalQuote;

                // Coverage
                totalQuote = (coverage.ToLower() == "full") ? (totalQuote + (totalQuote / 2)) : totalQuote;

                return Convert.ToInt32(totalQuote);
            }
        }
    }
}

Another Insurance Company (C#. NET)/AnotherInsuranceCompany/Views/Quote/Index.cshtml
<h2 class="card-header text-center">
  Start Quote!
</h2>
<h3 class="card-header text-center">Please tell us a little about yourself:</h3>
<br />


@using (Html.BeginForm("Apply", "Quote", FormMethod.Post))
{

    <table class="table">

      <tr>
        <th>First Name:</th>
        <td align="center"><input name="FirstName" type="text" class="form-control" placeholder="First Name" /></td>
      </tr>
      <tr>
        <th>Last Name:</th>
        <td align="center"><input name="LastName" type="text" class="form-control" placeholder="Last Name" /></td>
      </tr>
      <tr>
        <th>Email Address:</th>
        <td align="center"><input name="EmailAddress" type="email" class="form-control" placeholder="Email Address" /></td>
      </tr>
      <tr>
        <th>Date of Birth:</th>
        <td align="center"><input name="DateOfBirth" type="text" class="form-control" placeholder="MM/DD/YYYY" /></td>
      </tr>
      <tr>
        <th>Car Year:</th>
        <td align="center"><input name="CarYear" type="text" class="form-control" placeholder="YYYY" /></td>
      </tr>
      <tr>
        <th>Car Make:</th>
        <td align="center"><input name="CarMake" type="text" class="form-control" placeholder="ex. Subaru" /></td>
      </tr>
      <tr>
        <th>Car Model:</th>
        <td align="center"><input name="CarModel" type="text" class="form-control" placeholder="ex. BRZ" /></td>
      </tr>
      <tr>
        <th>Have you had a DUI?:</th>
        <td align="center"><input name="Dui" type="text" class="form-control" placeholder="Yes or No" /></td>
      </tr>
      <tr>
        <th>Speeding Tickets?:</th>
        <td align="center"><input name="Tickets" type="text" class="form-control" placeholder="No. of Tickets" /></td>
      </tr>
      <tr>
        <th>Full or Liability Coverage</th>
      <tr>
        <th>Choose One:</th>
        <td align="center"><input name="Coverage" type="text" class="form-control" placeholder="Full or Liability" /></td>
      </tr>
      <tr>
    </table>


  <div class="col-2" align="center">
    <button type="submit" class="btn btn-success col-md-3">Submit</button>
  </div>
  <br />
  <br />
  <div class="card bg-success img-rounded" align="center" style=" padding: 2px 2px;">
    <div class="mx-auto">
      <h3 class="text-center">
        Congratulations!  Your quote is:
        @ViewData["user.Total"]
      </h3>
    </div>
  </div>
}
<br />
<br />